[context.production]
    publish = "public"
    command = "yarn build"

[context.branch-deploy]
    publish = "/"
    command = "echo branch"

[context."v3"]
    publish = "public"
    command = "yarn build"