[context.production]
    publish = "public"
    command = "yarn build"

[context.branch-deploy]
    publish = "/"
    command = "echo branch"

[[redirects]]
  from = "https://blog.aaronconway.co.uk/*"
  to = "https://aaronconway.co.uk/blog/:splat"
  status = 200
  force = true